### ISSUE TITLE
Bug: Set security group to ALB

### ISSUE THREAD

**Issue by vnkiryushkin** [yandex-cloud/cluster-api-provider-yandex#25]
### Describe the bug

When deploying a cluster, the default security group is set to the ALB load balancer.

In the CRD for YandexCluster, Security Groups for loadBalancer are provided in the configuration. I have set up a deliberately working Security Group in capy-cluster.yml for YandexCluster (with all ports open):

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: YandexCluster
metadata:
  name: capy-cluster-17
  namespace: default
spec:
  folderID: b1gsm0k26v1l201n3ljr
  loadBalancer:
    listener:
      subnet:
        id: e9bj3s90g9hmf5jg7hnb
        zoneID: ru-central1-a
    type: ALB
    securityGroups: 
    - enps0ar5s3tiq57h8mk7
  network:
    id: enpgf5vu9dd7mac95q7b
```

But it looks like the controller ignores this setting and still creates an ALB with the default Security Group.

### Steps to reproduce

If you do not configure the rule for the security group beforehand, the cluster will not be deployed. There will be an error in the logs of the capy-controller-manager file:

```
ERROR   Reconciler error        {"controller": "yandexcluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "YandexCluster", "YandexCluster": {"name":"cluster-9-capy","namespace":"default"}, "namespace": "default", "name": "cluster-9-capy", "reconcileID": "5b34eec0-431d-472c-9a12-c8a2787aba8e", "error": "error reconciling load balancer: rpc error: code = InvalidArgument desc = Validation error:\nsecurity_group_ids: provided security groups should allow INGRESS traffic from well-known IP ranges for health checks\n"}
```

The necessary rule:

```
Ingress
TCP | 0-65535 | Security Group | Balancer
```

If the rule is configured, the cluster is deployed normally.

cluster-api-provider-yandex version: v1alpha1
kubernetes version:
  Client Version: v1.31.3
  Kustomize Version: v5.4.2
  Server Version: v1.27.3
OS: macOS 14.4
